### PR TITLE
Fix: Log requireFail results in yellow on stdout instead of red on stderr (fixes #142)

### LINKED ISSUE #142: Revisit requireFail color and message
It seems that some consumers are allergic to the color red - we should revisit the coloring and messaging of the `requireFail` log.

Ref https://github.com/zurb/foundation-sites/issues/10828
and https://github.com/gulpjs/gulp/issues/1631

### PR DESCRIPTION
**Pull request by phated**
@sttk what do you think of this change?  It seems like some tools interpret stderr wrong (like `husky`) and treat any output as a failure.  This change is mostly a cosmetic one but it does change some tests.

### CODE REVIEW

**Comment by sttk** [comment]
@phated I think this is good change. I'll review this.

File: test/exports-as-tasks.js [hunk 1]
```diff
@@ -21,11 +21,10 @@ describe('exports as tasks', function() {
 
     function cb(err, stdout) {
       expect(err).toEqual(null);
-      // Skipping stderr expectation because babel broke node 0.10
-      // expect(stderr).toEqual('');
```
Comment (sttk) [inline test/exports-as-tasks.js]: By this pr, stderr should become an empty string. Add its check code, please.

File: test/flags-require.js [hunk 2]
```diff
@@ -50,25 +50,25 @@ describe('flag: --require', function() {
...
+  it('warns if module doesn\'t exist', function(done) {
     runner({ verbose: false })
       .gulp('--require ./null-module.js', '--cwd ./test/fixtures/gulpfiles')
       .run(cb);
 
-    function cb(err, stdout, stderr) {
+    function cb(err, stdout) {
       expect(err).toEqual(null);
-      stderr = eraseLapse(eraseTime(stderr));
-      expect(stderr).toMatch('Failed to load external module ./null-module.js');
```
Comment (sttk) [inline test/flags-require.js]: By this pr, stderr should become an empty string. Add its check code, please.

**Comment by phated** [comment]
@sttk updated!

**Comment by sttk** [comment]
@phated Perfect! Thanks updating.

**Comment by sttk** [comment]
I've merged.
